(()=>{
  const {catalog,build,math,frac}=window.RAZBOR_TRAINING,$=s=>document.querySelector(s),q=new URLSearchParams(location.search);
  const grade=Number(q.get('grade')),topic=q.get('topic'),level=Number(q.get('level')),count=Number(q.get('count')),seed=Number(q.get('seed')),student=(q.get('student')||'Ученик').slice(0,80);
  const valid=catalog[topic]?.grade===grade&&catalog[topic]?.skills[level]&&Number.isInteger(count)&&count>=3&&count<=10&&Number.isInteger(seed)&&student.length;
  if(!valid){$('#testScreen').hidden=true;$('#error').hidden=false;$('#error').textContent='Ссылка на тренировку неполная или повреждена. Попроси учителя прислать её ещё раз.';return}
  const skills=catalog[topic].skills[level],tasks=Array.from({length:count},(_,i)=>({skill:i%skills.length,task:build(topic,level,i%skills.length,seed+i)}));
  const state={testIndex:0,correct:0,wrongSkills:new Set(),answered:false,fixSkills:[],fixIndex:0,phase:'guided',step:0,task:null,hintStage:0,wrong:0};
  function unwrap(value){const s=value.trim();return s.startsWith('(')&&s.endsWith(')')?s.slice(1,-1):s}
  function topSlash(value){let depth=0;for(let i=0;i<value.length;i++){if(value[i]==='(')depth++;else if(value[i]===')')depth--;else if(value[i]==='/'&&depth===0)return i}return-1}
  function formatClause(raw){let prefix='',value=raw.trim();const relation=[...value.matchAll(/(?:=|≠)/g)].pop();if(relation){const cut=relation.index+relation[0].length;prefix=value.slice(0,cut)+' ';value=value.slice(cut).trim()}const slash=topSlash(value);if(slash<0)return math(prefix+value);return '<span class="math-prefix">'+math(prefix)+'</span>'+frac(unwrap(value.slice(0,slash)),unwrap(value.slice(slash+1)))}
  const formatAnswer=raw=>String(raw).split(';').map(formatClause).join('<span class="math-separator">; </span>');
  const shuffle=xs=>xs.map(x=>[Math.random(),x]).sort((a,b)=>a[0]-b[0]).map(x=>x[1]);
  function answerButton(value,onClick){const b=document.createElement('button');b.type='button';b.className='answer';b.innerHTML=formatAnswer(value);b.onclick=()=>onClick(value,b);return b}
  function setRoute(stage){['routeTest','routeResult','routeFix'].forEach((id,i)=>{$('#'+id).className=i<stage?'done':i===stage?'active':''})}
  $('#welcome').textContent=student+', это твоя тренировка';$('#routeCaption').textContent=grade+' класс · '+catalog[topic].name+' · уровень '+level+'.0';document.title=student+' · '+catalog[topic].name;
  function renderTest(){state.answered=false;const item=tasks[state.testIndex],step=item.task.finalStep;$('#testCounter').textContent='Задание '+(state.testIndex+1)+' из '+count;$('#testProgressText').textContent=skills[item.skill];$('#progressFill').style.width=(state.testIndex/count*100)+'%';$('#testInstruction').textContent=item.task.instruction;$('#testFormula').innerHTML=item.task.formula;$('#testQuestion').textContent=step.question;$('#testFeedback').hidden=true;$('#testFeedback').className='feedback';$('#testNext').hidden=true;$('#testChoices').replaceChildren(...shuffle(step.choices).map(v=>answerButton(v,answerTest)))}
  function answerTest(value,button){if(state.answered)return;state.answered=true;const item=tasks[state.testIndex],correct=value===item.task.finalStep.answer;[...document.querySelectorAll('#testChoices .answer')].forEach(b=>b.disabled=true);button.classList.add(correct?'correct':'wrong');if(correct){state.correct++;$('#testFeedback').className='feedback good';$('#testFeedback').innerHTML='<strong>Верно.</strong> Ответ засчитан.'}else{state.wrongSkills.add(item.skill);$('#testFeedback').className='feedback neutral';$('#testFeedback').innerHTML='<strong>Ответ принят.</strong> Этот способ решения появится в работе над ошибками.'}$('#testFeedback').hidden=false;$('#testNext').hidden=false;$('#testNext').textContent=state.testIndex===count-1?'Посмотреть результат →':'Следующее задание →'}
  $('#testNext').onclick=()=>{if(state.testIndex<count-1){state.testIndex++;renderTest();return}showResult()};
  function showResult(){setRoute(1);$('#testScreen').hidden=true;$('#resultScreen').hidden=false;$('#progressFill').style.width='100%';state.fixSkills=[...state.wrongSkills];const missed=state.fixSkills.length;$('#resultMark').textContent=state.correct+'/'+count;$('#resultTitle').textContent=missed?student+', тест пройден. Теперь разберём ошибки':student+', всё верно!';$('#resultText').textContent=missed?'Ниже отмечены навыки, которые стоит потренировать. Для каждого будет пошаговый разбор и новый самостоятельный пример.':'Ты уверенно справился со всеми заданиями. Можно закрепить тему новым вариантом теста.';$('#skillResults').replaceChildren(...skills.map((name,i)=>{const row=document.createElement('div'),needs=state.wrongSkills.has(i);row.className='skill-result '+(needs?'needs-work':'ok');row.innerHTML='<strong>'+name+'</strong><span>'+(needs?'Нужно разобрать':'Освоено')+'</span>';return row}));$('#startFix').textContent=missed?'Начать работу над ошибками →':'Пройти новый вариант';$('#startFix').onclick=missed?startFix:repeatTest;window.scrollTo({top:0,behavior:'smooth'})}
  function startFix(){setRoute(2);$('#resultScreen').hidden=true;$('#fixScreen').hidden=false;state.fixIndex=0;startFixTask('guided')}
  function startFixTask(phase){state.phase=phase;state.step=0;state.hintStage=0;state.wrong=0;const skill=state.fixSkills[state.fixIndex],offset=phase==='guided'?1000:2000;state.task=build(topic,level,skill,seed+offset+state.fixIndex);renderFix()}
  const activeSteps=()=>state.phase==='guided'?state.task.steps:[state.task.finalStep];
  function renderFix(){const skill=state.fixSkills[state.fixIndex],steps=activeSteps(),step=steps[state.step];state.hintStage=0;state.wrong=0;$('#fixCounter').textContent='Ошибка '+(state.fixIndex+1)+' из '+state.fixSkills.length;$('#fixSkill').textContent=skills[skill];$('#fixPhase').textContent=state.phase==='guided'?'Разбор с поддержкой':'Самостоятельно';$('#instruction').textContent=state.task.instruction;$('#formula').innerHTML=state.task.formula;$('#rule').hidden=state.phase!=='guided';$('#rule').textContent='Правило: '+state.task.rule;$('#stepCount').textContent='Шаг '+(state.step+1)+' из '+steps.length;$('#question').textContent=step.question;$('#feedback').hidden=true;$('#feedback').className='feedback';$('#next').hidden=true;$('#hint').hidden=state.phase!=='guided';$('#hint').textContent='Подсказка к шагу';$('#choices').replaceChildren(...shuffle(step.choices).map(v=>answerButton(v,answerFix)))}
  function targetedHint(step,chosen){const correct=String(step.answer),picked=String(chosen);if(correct.includes(';')&&!picked.includes(';'))return 'Ответ неполный: вернись к исходным знаменателям и допиши все запрещённые значения.';if(!correct.includes('ограничений нет')&&picked.includes('ограничений нет'))return 'Ограничения определяются по исходной записи и сохраняются после сокращения.';if(correct.includes('−')!==picked.includes('−'))return 'Проверь знак отдельно: минус нельзя терять при преобразовании.';if(correct.includes('/')&&!picked.includes('/'))return 'Сокращать можно только общий множитель числителя и знаменателя.';return 'Сосредоточься на действии «'+step.title.toLowerCase()+'». '+step.why}
  function answerFix(value,button){const step=activeSteps()[state.step],all=[...document.querySelectorAll('#choices .answer')];if(value===step.answer){button.classList.add('correct');all.forEach(b=>b.disabled=true);$('#feedback').hidden=false;$('#feedback').className='feedback good';$('#feedback').innerHTML='<strong>Верно.</strong> '+math(step.why);$('#next').hidden=false;$('#next').textContent=state.step===activeSteps().length-1?(state.phase==='guided'?'Попробовать новый пример самостоятельно →':state.fixIndex===state.fixSkills.length-1?'Завершить работу ✓':'Перейти к следующей ошибке →'):'Следующий шаг →';return}button.classList.add('wrong');button.disabled=true;state.wrong++;$('#feedback').hidden=false;$('#feedback').className='feedback bad';$('#feedback').innerHTML='<strong>Что проверить:</strong> '+math(state.phase==='guided'?targetedHint(step,value):'Вспомни алгоритм: '+state.task.rule+' Проверь каждый шаг и ограничения исходной записи.');if(state.phase==='guided'&&state.wrong>1){$('#hint').hidden=false;$('#hint').textContent='Показать следующий ориентир'}}
  $('#hint').onclick=()=>{const step=activeSteps()[state.step];state.hintStage++;$('#feedback').hidden=false;$('#feedback').className='feedback hint-feedback';if(state.hintStage===1){$('#feedback').innerHTML='<strong>С чего начать:</strong> '+math(step.why)+'<br><span>Выполни только действие «'+math(step.title.toLowerCase())+'».</span>';$('#hint').textContent='Ещё один ориентир';return}$('#feedback').innerHTML='<strong>Промежуточная запись:</strong> должно получиться <span class="inline-answer">'+formatAnswer(step.answer)+'</span>.<br><span>Сравни со своей записью и назови использованное правило.</span>';$('#hint').hidden=true};
  $('#next').onclick=()=>{if(state.step<activeSteps().length-1){state.step++;renderFix();return}if(state.phase==='guided'){startFixTask('independent');return}if(state.fixIndex<state.fixSkills.length-1){state.fixIndex++;startFixTask('guided');return}finishFix()};
  function finishFix(){setRoute(3);$('#fixScreen').hidden=true;$('#finishScreen').hidden=false;$('#finishTitle').textContent=student+', работа над ошибками завершена';$('#finishText').textContent='Ты разобрал ошибочные навыки и решил по каждому новый пример самостоятельно. Теперь можно пройти свежий тест по этой же теме.';window.scrollTo({top:0,behavior:'smooth'})}
  function repeatTest(){const url=new URL(location.href);url.searchParams.set('seed',String(seed+5000));location.href=url.href}
  $('#repeatTest').onclick=repeatTest;renderTest();
})();
