(()=>{
  const {catalog,build,math,frac}=window.RAZBOR_TRAINING;
  const $=s=>document.querySelector(s);
  const state={grade:7,topic:'numeric',level:2,skill:0,seed:Date.now()%100000,phase:'guided',step:0,task:null,hintStage:0,wrong:0};
  const saved=()=>{try{return JSON.parse(localStorage.getItem('razbor-public-progress'))||{}}catch{return{}}};
  const markDone=()=>{const p=saved();p[state.topic+'-'+state.level+'-'+state.skill]=true;localStorage.setItem('razbor-public-progress',JSON.stringify(p))};
  const topicIds=()=>Object.keys(catalog).filter(id=>catalog[id].grade===state.grade);
  function button(text,active,onClick,cls='choice-btn'){const b=document.createElement('button');b.type='button';b.className=cls+(active?' active':'');b.textContent=text;b.onclick=onClick;return b}
  function unwrap(value){const s=value.trim();return s.startsWith('(')&&s.endsWith(')')?s.slice(1,-1):s}
  function topSlash(value){let depth=0;for(let i=0;i<value.length;i++){if(value[i]==='(')depth++;else if(value[i]===')')depth--;else if(value[i]==='/'&&depth===0)return i}return-1}
  function formatClause(raw){let prefix='',value=raw.trim();const relation=[...value.matchAll(/(?:=|≠)/g)].pop();if(relation){const cut=relation.index+relation[0].length;prefix=value.slice(0,cut)+' ';value=value.slice(cut).trim()}const slash=topSlash(value);if(slash<0)return math(prefix+value);return '<span class="math-prefix">'+math(prefix)+'</span>'+frac(unwrap(value.slice(0,slash)),unwrap(value.slice(slash+1)))}
  const formatAnswer=raw=>String(raw).split(';').map(formatClause).join('<span class="math-separator">; </span>');
  function renderNav(){$('#grades').replaceChildren(...[7,8].map(g=>button(g+' класс',state.grade===g,()=>{state.grade=g;state.topic=topicIds()[0];state.level=2;renderNav();renderSkills()})));$('#topics').replaceChildren(...topicIds().map(id=>button(catalog[id].name,state.topic===id,()=>{state.topic=id;renderNav();renderSkills()},'topic-btn')));$('#levels').replaceChildren(...[2,3].map(l=>button('Уровень '+l+'.0',state.level===l,()=>{state.level=l;renderNav();renderSkills()})));$('#topicCaption').textContent=state.grade+' класс · '+catalog[state.topic].name}
  function renderSkills(){const items=catalog[state.topic].skills[state.level],p=saved();$('#progressCaption').textContent=items.filter((_,i)=>p[state.topic+'-'+state.level+'-'+i]).length+' из '+items.length+' навыков пройдено';$('#skills').replaceChildren(...items.map((name,i)=>{const b=button('',false,()=>start(i),'skill-card');b.innerHTML='<span class="skill-num">'+(i+1)+'</span><span><strong>'+name+'</strong><small>Разбор по шагам → самостоятельный пример</small></span>'+(p[state.topic+'-'+state.level+'-'+i]?'<span class="done">✓ Пройдено</span>':'');return b}))}
  const shuffle=xs=>xs.map(x=>[Math.random(),x]).sort((a,b)=>a[0]-b[0]).map(x=>x[1]);
  function start(skill,phase='guided'){state.skill=skill;state.phase=phase;state.step=0;state.task=build(state.topic,state.level,skill,state.seed++);$('#home').hidden=true;$('#practice').hidden=false;renderTask();window.scrollTo({top:0,behavior:'smooth'})}
  const activeSteps=()=>state.phase==='guided'?state.task.steps:[state.task.finalStep];
  function renderTask(){const task=state.task,steps=activeSteps(),step=steps[state.step];state.hintStage=0;state.wrong=0;$('#context').textContent=state.grade+' класс · '+catalog[state.topic].name+' · '+catalog[state.topic].skills[state.level][state.skill];$('#title').textContent=task.title;$('#phase').textContent=state.phase==='guided'?'Разбор с поддержкой':'Самостоятельно';$('#instruction').textContent=task.instruction;$('#formula').innerHTML=task.formula;$('#rule').hidden=state.phase!=='guided';$('#rule').textContent='Правило: '+task.rule;$('#stepCount').textContent='Шаг '+(state.step+1)+' из '+steps.length;$('#question').textContent=step.question;$('#feedback').hidden=true;$('#feedback').className='feedback';$('#next').hidden=true;$('#hint').hidden=state.phase!=='guided';$('#hint').textContent='Подсказка к шагу';$('#choices').replaceChildren(...shuffle(step.choices).map(value=>{const b=button('',false,()=>answer(value,b),'answer');b.innerHTML=formatAnswer(value);return b}))}
  function targetedHint(step,chosen){const correct=String(step.answer),picked=String(chosen);if(correct.includes(';')&&!picked.includes(';'))return 'Ты нашёл преобразованное выражение, но ответ неполный. Вернись к исходным знаменателям и допиши все запрещённые значения.';if(!correct.includes('ограничений нет')&&picked.includes('ограничений нет'))return 'Ограничения определяются по исходной записи. Даже после сокращения значение, обращавшее исходный знаменатель в ноль, остаётся запрещённым.';if(correct.includes('−')!==picked.includes('−'))return 'Проверь знак отдельно: при переносе, раскрытии скобок или работе с противоположными знаменателями минус нельзя терять.';if(correct.includes('/')&&!picked.includes('/'))return 'После преобразования должна остаться дробь. Сокращать можно только общий множитель числителя и знаменателя, а не отдельные слагаемые.';return 'Сосредоточься только на действии «'+step.title.toLowerCase()+'». '+step.why}
  function answer(value,b){const step=activeSteps()[state.step],all=[...document.querySelectorAll('.answer')];if(value===step.answer){b.classList.add('correct');all.forEach(x=>x.disabled=true);$('#feedback').hidden=false;$('#feedback').className='feedback good';$('#feedback').innerHTML='<strong>Верно.</strong> '+math(step.why);$('#next').hidden=false;$('#next').textContent=state.step===activeSteps().length-1?(state.phase==='guided'?'Попробовать самостоятельно →':'Завершить навык ✓'):'Следующий шаг →';return}b.classList.add('wrong');b.disabled=true;state.wrong++;$('#feedback').hidden=false;$('#feedback').className='feedback bad';const explanation=state.phase==='guided'?targetedHint(step,value):'Вспомни алгоритм: '+state.task.rule+' Проверь преобразование и ограничения исходной записи отдельно.';$('#feedback').innerHTML='<strong>Что проверить:</strong> '+math(explanation);if(state.phase==='guided'&&state.wrong>1){$('#hint').hidden=false;$('#hint').textContent='Показать следующий ориентир'}}
  $('#hint').onclick=()=>{const step=activeSteps()[state.step];state.hintStage++;$('#feedback').hidden=false;$('#feedback').className='feedback hint-feedback';if(state.hintStage===1){$('#feedback').innerHTML='<strong>С чего начать:</strong> '+math(step.why)+'<br><span>Выполни только действие «'+math(step.title.toLowerCase())+'», не переходя к следующему.</span>';$('#hint').textContent='Ещё один ориентир';return}$('#feedback').innerHTML='<strong>Промежуточная запись:</strong> на этом шаге должно получиться <span class="inline-answer">'+formatAnswer(step.answer)+'</span>.<br><span>Сравни её со своей записью и объясни, какое правило привело к этому результату.</span>';$('#hint').hidden=true};
  $('#next').onclick=()=>{if(state.step<activeSteps().length-1){state.step++;renderTask();return}if(state.phase==='guided'){start(state.skill,'independent');return}markDone();$('#practice').hidden=true;$('#home').hidden=false;renderSkills();window.scrollTo({top:0,behavior:'smooth'})};
  $('#back').onclick=()=>{$('#practice').hidden=true;$('#home').hidden=false;renderSkills()};renderNav();renderSkills();
})();
