(() => {
  const $=s=>document.querySelector(s),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const math=s=>escape(s).replace(/\^(\d+)/g,'<sup>$1</sup>').replace(/(\d)\.(\d)/g,'$1,$2');
  function graph(g){const xmax=Math.max(5,Math.abs(g.holeX||0)+2),ymax=Math.max(8,Math.abs(g.slope*xmax+g.intercept),Math.abs(-g.slope*xmax+g.intercept))+2,px=x=>200+165*x/xmax,py=y=>120-90*y/ymax;let hole='';if(g.holeX!==null){const y=g.slope*g.holeX+g.intercept;hole='<circle cx="'+px(g.holeX)+'" cy="'+py(y)+'" r="5" fill="white" stroke="#df334b" stroke-width="2"/><text x="'+Math.min(285,px(g.holeX)+8)+'" y="'+Math.max(32,py(y)-10)+'">('+g.holeX+'; '+String(y).replace('.',',')+')</text>';}return '<figure class="graph"><svg viewBox="0 0 400 240" role="img" aria-label="'+(g.holeX===null?'График прямой':'Прямая с выколотой точкой')+'"><path d="M30 120H375 M200 220V20" stroke="#8490a5"/><text x="378" y="118">x</text><text x="208" y="20">y</text><text x="204" y="136">0</text><text x="35" y="136">−'+xmax+'</text><text x="342" y="136">'+xmax+'</text><text x="206" y="35">'+ymax+'</text><line x1="'+px(-xmax)+'" y1="'+py(-g.slope*xmax+g.intercept)+'" x2="'+px(xmax)+'" y2="'+py(g.slope*xmax+g.intercept)+'" stroke="#2b59ff" stroke-width="2.5"/>'+hole+'</svg><figcaption>'+(g.holeX===null?'Две проверенные точки лежат на этой прямой.':'Пустой кружок означает, что эта точка исключена из графика исходной функции.')+'</figcaption></figure>';}
  let profile=null,work=null,skill=null,task=null;
  async function api(route,body){const response=await fetch('api/'+route,{credentials:'same-origin',...(body!==undefined?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{})});const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||'Не удалось выполнить действие');return data;}
  function view(name){['login','dashboard','practice','unavailable'].forEach(x=>$('#'+x).hidden=x!==name);$('#globalError').textContent='';}
  async function dashboard(){profile=await api('student/me');$('#greeting').textContent=profile.student.name+', твои работы';$('#logout').hidden=false;$('#teacherLink').hidden=true;
    $('#assignments').innerHTML=profile.assignments.length?profile.assignments.map(a=>'<article class="card assignment"><div class="meta">'+a.grade+' класс · '+escape(a.topicName)+' · '+a.level+'.0</div><h2>'+escape(a.title)+'</h2><div class="meta">Самостоятельных примеров: '+a.correctCount+' из '+a.taskCount+'</div>'+(a.status==='completed'?'<p class="completed">✓ Работа выполнена. Новую откроет учитель.</p>':'<div class="skills">'+a.skills.map(s=>'<div class="skill-row"><span>'+escape(s.name)+'<br><small class="meta">Проверено: '+(s.completed||0)+' из '+(s.target||1)+'</small></span>'+(s.completed>=s.target?'<span class="completed">✓ Выполнено</span>':'<button class="primary" data-work="'+a.id+'" data-skill="'+s.id+'">Начать разбор →</button>')+'</div>').join('')+'</div>')+'</article>').join(''):'<div class="empty">Пока нет открытых работ. Попроси учителя назначить тренировку.</div>';
    document.querySelectorAll('[data-work]').forEach(b=>b.onclick=()=>{work=profile.assignments.find(a=>a.id===Number(b.dataset.work));skill=Number(b.dataset.skill);start('guided').catch(fail);});view('dashboard');}
  function fail(e){$('#globalError').textContent=e.message;}
  async function start(phase){task=await api('student/tasks',{assignmentId:work.id,skillId:skill,phase});renderTask();view('practice');window.scrollTo({top:0,behavior:'smooth'});}
  function renderTask(){$('#context').textContent=work.topicName+' · '+work.level+'.0';$('#phase').textContent=task.phase==='guided'?'1 · Разбор с поддержкой':'2 · Самостоятельная проверка';$('#skill').textContent=task.skill;$('#taskTitle').textContent=task.title;$('#instruction').textContent=task.instruction||'';$('#formula').innerHTML=task.formula;$('#rule').hidden=task.phase!=='guided';$('#rule').textContent=task.rule||'';$('#sample').hidden=task.phase!=='guided';$('#sample').open=false;
    if(task.sample)$('#sampleBody').innerHTML='<div class="formula">'+task.sample.formula+'</div>'+task.sample.steps.map((s,i)=>'<div class="sample-step"><b>'+ (i+1)+'. '+escape(s.title)+'</b><div>'+math(s.answer)+'</div><p>'+escape(s.why)+'</p></div>').join('')+(task.sample.graph?graph(task.sample.graph):'');
    $('#stepCount').textContent=task.phase==='guided'?'Шаг '+(task.stepIndex+1)+' из '+task.stepCount:'Сначала реши на бумаге. Подсказок в проверке нет.';$('#question').textContent=task.question;$('#feedback').hidden=!task.passed;$('#feedback').className='feedback';$('#feedback').textContent=task.passed?'Этот шаг уже выполнен. Можно продолжать.':'';$('#hints').innerHTML='';$('#next').hidden=!task.passed;$('#next').textContent=task.stepIndex===task.stepCount-1?(task.phase==='guided'?'Перейти к самостоятельной проверке →':'Посмотреть результат →'):'Следующий шаг →';$('#hint').hidden=task.phase!=='guided';$('#hint').disabled=task.passed||task.hintStage>=3;$('#support').hidden=task.phase!=='independent';
    $('#choices').innerHTML=task.choices.map((c,i)=>'<button class="choice" type="button" data-choice="'+c.id+'"><b aria-hidden="true">'+['А','Б','В','Г','Д'][i]+'</b><span>'+math(c.text)+'</span></button>').join('');
    document.querySelectorAll('[data-choice]').forEach(b=>{b.disabled=task.passed;b.onclick=async()=>{try{const result=await api('student/tasks/'+task.id+'/answer',{choiceId:b.dataset.choice});$('#feedback').hidden=false;$('#feedback').className='feedback'+(result.correct?'':' bad');$('#feedback').textContent=result.feedback;if(result.graph){const plot=document.createElement('div');plot.innerHTML=graph(result.graph);$('#feedback').append(plot);}b.classList.add(result.correct?'correct':'wrong');b.disabled=true;if(result.correct){document.querySelectorAll('[data-choice]').forEach(x=>x.disabled=true);$('#next').hidden=false;$('#hint').disabled=true;$('#next').focus({preventScroll:true});}}catch(e){fail(e);}};});}
  $('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';try{await api('student/login',{code:$('#code').value});await dashboard();}catch(err){$('#loginError').textContent=err.message;}};
  $('#logout').onclick=async()=>{await api('logout',{});profile=null;$('#logout').hidden=true;$('#teacherLink').hidden=false;view('login');};
  $('#back').onclick=()=>dashboard().catch(fail);
  $('#support').onclick=()=>start('guided').catch(fail);
  $('#hint').onclick=async()=>{try{const h=await api('student/tasks/'+task.id+'/hint',{});const p=document.createElement('p');p.textContent='Подсказка '+h.stage+'. '+h.text;$('#hints').append(p);$('#hint').disabled=h.stage>=3;}catch(e){fail(e);}};
  $('#next').onclick=async()=>{try{const next=await api('student/tasks/'+task.id+'/next',{});if(next.finished){if(task.phase==='guided')await start('independent');else await dashboard();}else{task=next;renderTask();$('#question').tabIndex=-1;$('#question').focus({preventScroll:true});}}catch(e){fail(e);}};
  (async()=>{if(location.protocol!=='https:'&&!['localhost','127.0.0.1','[::1]'].includes(location.hostname)){location.replace('https://'+location.host+location.pathname+location.search);return;}try{const health=await api('health');if(!health.personalAccess)throw Error('No personal server');$('#teacherLink').hidden=false;if(health.role==='teacher'){location.replace('teacher.html');return;}if(health.role==='student')await dashboard();else view('login');}catch{view('unavailable');}})();
})();
